# Generated by Django 5.1.8 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0098_merge_20260513_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositeevalchild',
            name='config',
            field=models.JSONField(blank=True, help_text='Per-binding child eval runtime config overrides.', null=True),
        ),
    ]
