# Generated by Django 5.1.8 on 2026-05-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0099_backfill_empty_eval_template_versions'),
        ('model_hub', '0099_compositeevalchild_config'),
    ]

    operations = [
    ]
