# Generated by Django 5.1.8 on 2026-05-20 11:11

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


# Status priority for choosing which duplicate row survives. Lower index wins.
# Migration uses raw strings (not the ConnectionStatus enum) because data
# migrations historically resolve models without their app-level constants.
_STATUS_PRIORITY = {"active": 0, "backfilling": 1, "syncing": 2, "paused": 3}

# Snapshot of ACTION_ONLY_PLATFORMS at the time of this migration. Frozen
# literal — adding a new action-only platform later must come with its own
# dedup + constraint-extension migration; do not retroactively rewrite this.
_ACTION_ONLY_PLATFORMS_SNAPSHOT = ["linear"]


def _dedupe_action_only_connections(apps, schema_editor):
    """Soft-delete duplicate live action-only connections per (org, workspace, platform).

    The new partial unique constraint forbids more than one live action-only
    connection per workspace per platform. Existing rows that violate it
    would block AddConstraint, so we collapse each duplicate group down to a
    single surviving row first. Survivor preference: best status, then newest.
    """
    IntegrationConnection = apps.get_model("integrations", "IntegrationConnection")

    live = IntegrationConnection.objects.filter(
        platform__in=_ACTION_ONLY_PLATFORMS_SNAPSHOT, deleted=False
    ).order_by("organization_id", "workspace_id", "platform", "-created_at")

    groups: dict[tuple, list] = {}
    for conn in live:
        key = (conn.organization_id, conn.workspace_id, conn.platform)
        groups.setdefault(key, []).append(conn)

    now = timezone.now()
    for rows in groups.values():
        if len(rows) <= 1:
            continue
        rows.sort(
            key=lambda r: (
                _STATUS_PRIORITY.get(r.status, 99),
                -int(r.created_at.timestamp()),
            )
        )
        for loser in rows[1:]:
            loser.deleted = True
            loser.deleted_at = now
            loser.save(update_fields=["deleted", "deleted_at"])


def _noop_reverse(apps, schema_editor):
    """Soft-deleted rows are intentionally left as-is on rollback —
    restoring them would re-introduce the constraint violation."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20260407_1927'),
        ('integrations', '0003_linear_integration'),
        ('tracer', '0077_merge_20260514_1559'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_dedupe_action_only_connections, _noop_reverse),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__in', ['linear']), ('deleted', False)), fields=('organization', 'workspace', 'platform'), name='uq_intconn_org_ws_action_only_active'),
        ),
    ]
